[service]
name = "nanomdm"

# Start Command (บังคับมี -ca)
start = """
/app/nanomdm \
  -http :9000 \
  -ca /data/ca/ca.pem \
  -storage postgres \
  -storage-dsn "postgresql://postgres:xupQWGgNgRoAIwXWlhtFFhEvMtohIupS@postgres.railway.internal:5432/railway"
"""

[volumes]
mounts = [
  { volume = "nanomdm-data", path = "/data" }
]
